#+title: Nim + musl + pcre + ssl
#+author: Kaushal Modi

[[https://travis-ci.org/kaushalmodi/hello_musl][https://travis-ci.org/kaushalmodi/hello_musl.svg?branch=master]]

This repo contains a generic [[https://github.com/kaushalmodi/hello_musl/blob/master/config.nims][~config.nims~]] that adds a Nim
"sub-command" or task named *musl*. You can simply add that file to
your Nim project, and run ~nim musl foo.nim~ with optional ~-d:pcre~
and/or ~-d:ssl~ switches (assuming that the below prerequisites are
met).

* Prerequisites
- OS: One of Linux x86 (32/64), ARM (32/64), MIPS (32/64), PowerPC
  (32/64), S390X, SuperH, Microblaze, OpenRISC ([[https://www.musl-libc.org/intro.html][ref]])
- Nim: [[https://nim-lang.org/]] (built from [[https://github.com/nim-lang/Nim/tree/devel][*devel*]] branch as of <2018-09-13 Thu>)
- *musl* library: [[https://www.musl-libc.org/download.html]]
** Optional
These optional command-line utilities for binary size optimization
will be run automatically one by one, if present.
- ~strip~ (from ~binutils~): [[https://sourceware.org/binutils/docs/binutils/strip.html]]
- ~upx~: [[https://github.com/upx/upx]]
* Generating static binary
** For this example ~hello_musl~ project
1. ~git clone https://github.com/kaushalmodi/hello_musl~
2. ~cd hello_musl~
3. Example of static linking with just musl lib: ~nim musl src/hello_musl.nim~
   - That will generate ~hello_musl~ binary in ~src/~ directory.
   - ~file ./src/hello_musl~ will print:
     #+begin_example
     src/hello_musl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
     #+end_example
   - ~./src/hello_musl~ will print:
     #+begin_example
     Hello, World!
     #+end_example
4. Example of static linking with musl+pcre libs: ~nim musl -d:pcre src/hello_musl_pcre.nim~
   - That will generate ~hello_musl_pcre~ binary in ~src/~ directory.
   - ~file ./src/hello_musl_pcre~ will print:
     #+begin_example
     src/hello_musl_pcre: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
     #+end_example
   - ~./src/hello_musl_pcre~ will print:
     #+begin_example
     Hello, World!
     Bye, World!
     #+end_example
5. Example of static linking with musl+ssl libs: ~nim musl -d:ssl src/hello_musl_ssl.nim~
   - That will generate ~hello_musl_ssl~ binary in ~src/~ directory.
   - ~file ./src/hello_musl_ssl~ will print:
     #+begin_example
     src/hello_musl_ssl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped
     #+end_example
   - ~./src/hello_musl_ssl~ will print:
     #+begin_example
     {"name":"Kaushal Modi","type":"card","url":"https://scripter.co/"}
     {
       "name": "Kaushal Modi",
       "type": "card",
       "url": "https://scripter.co/"
     }
     "Kaushal Modi"
     #+end_example


- Note :: When building with ~-d:ssl~, a statically linked version of
          OpenSSL library is *first* built with
          ~-DOPENSSL_NO_SECURE_MEMORY~ Configure option, because of an
          [[https://github.com/openssl/openssl/issues/7207#issuecomment-420814524][issue with it getting built using MUSL]]. Do not use that
          ~-d:ssl~ switch if you do not want to enable that insecure
          option.
** For your Nim project
- Copy the [[https://github.com/kaushalmodi/hello_musl/blob/master/config.nims][~config.nims~]] to your Nim project.
- While being the same directory as ~config.nims~, do:
  #+begin_example
  nim musl <path/to/your/nim/file>         # without static pcre lib linking
  nim musl -d:pcre <path/to/your/nim/file> # *with* static pcre lib linking
  nim musl -d:ssl <path/to/your/nim/file>  # *with* static openssl lib linking
  #+end_example
* References
- [[https://github.com/nim-lang/Nim/wiki/Using-nimscript-for-configuration]]
- [[https://nim-lang.org/docs/nims.html]]
  - [[https://nim-lang.org/docs/nimscript.html]]
- [[https://hookrace.net/blog/nim-binary-size/#using-the-c-standard-library]]
- [[https://www.reddit.com/r/programming/comments/2wk7q6/static_linking_with_nim/corwtl7/]]
* TODO Todo-List
- [ ] Figure out how to have ~nimble install~ install the binary
  generated by ~nim musl~.
- [X] Don't hard-code the ~muslGcc~ const in ~config.nims~
- [X] Not require ~hello_musl.nimble~
  - Currently that is needed just to add the ~-d:musl~ and
    ~-d:release~ switches, and then to auto-run ~strip -s~.
  - So to remove dependency on this file, I need to figure out how to
    get the current /foo.nim/ file name from within the ~config.nims~.
  - Eventual goal is to reuse the same ~config.nims~ for all
    projects. So I cannot hardcode the ~pkgName~ as I do in
    ~hello_musl.nimble~.
